### PR TITLE
Added #3DBenchy as 3MF sample file format

### PR DESCRIPTION
**Pull request by PauloKiefe**
According to conversation we submitted the #3DBenchy 3D printing benchmark file (in .3mf format) for inclusion to this repository.

### CODE REVIEW

**Comment by t-paul** [comment]
Good idea. I'm a bit confused regarding the license though. The website (and various other places, e.g. Thingiverse) states the model is licensed as `CC-BY-ND` but the github repo has a license file claiming `CC0`.

As this seems to come from the official repo, you are obviously free to license this however you like, it still seems strange.

Edit: Fixed typo, [license](http://3dbenchy.com/license/) is `-ND` not `-NC`

**Comment by teppix** [comment]
@t-paul I created the 3dbenchy repo, and I realize now that I've selected the wrong license there. Will have to correct that.

@PauloKiefe knows better what license is the right one, but I think it should be Attribution, No Derivatives.

**Comment by PauloKiefe** [comment]
@t-paul Thanks for asking about the license. You are correct that the #3DBenchy model is released under a Creative Commons - Attribution - No Derivatives license. The purpose of the file is to be used as a calibration tool, and therefore it is important that only one version is published to keep test results consistent between 3D printers, settings and materials.

Nevertheless anyone is free to use and modify and adapt #3DBenchy for their own needs and tests. The "no derivative" part of the license just relates to re-publishing a modified version of #3DBenchy 3D file. There is an extended explanation about this at [3dbenchy.com/license](http://3dbenchy.com/license/).

**Comment by t-paul** [comment]
Sure, the license makes totally sense, especially for the use-case of being a reference. As said before, I like the model, it a very cool 3d printing test. It would be a nice addition here. I think I've printed 3 myself so far :-). (also fixed the ND vs. NC typo in my previous comment)

I have no idea what the strategy for this repo is, which is why I created issue #3 to ask for clarification. If the wish is to maybe distribute the sample files e.g. in Linux distributions, it needs to be clear what file is covered by what license. I have no idea if the `-ND` part would be an issue there, but that's for someone else to discuss. I just wanted to point out that it helps a lot if licenses are clear as finding out a couple of years later is a very tedious task if possible at all.

I'm only interested as I'm using `lib3mf` in OpenSCAD, so I'm going to ask Linux distribution packagers to include `lib3mf`, so the more things are clarified before, the easier it will be to find people willing to package.

**Comment by PauloKiefe** [comment]
Thanks Paul for the clarification about the licence. Please let me know if I can help out in any way. :)

**Comment by pencerw** [comment]
All, I believe that since this repository is BSD-2 we are barred from including CC-BY-ND samples like #3DBenchy. However, we are currently in the process of rebuilding this repository with many other useful sample files, which will hopefully address the intent of this PR.

**Pull request closed without merging**
